services:

  # fake bobcat miner
  fancy-awesome-bobcat:
    image: fancy-awesome-bobcat
    hostname: fancy-awesome-bobcat
    container_name: fancy-awesome-bobcat
    ports:
      - "80:80"
    build:
      context: ./fancy-awesome-bobcat
      dockerfile: ./Dockerfile

  # bobcat-miner-python command line tools
  bobcat-miner-python:
    image: bobcat-miner-python
    hostname: bobcat-miner-python
    container_name: bobcat-miner-python
    environment:
      BOBCAT_HOSTNAME: "fancy-awesome-bobcat"
      BOBCAT_ANIMAL: "fancy-awesome-bobcat"
      BOBCAT_DRY_RUN: "TRUE"
      BOBCAT_VERBOSE: "FALSE"
      BOBCAT_TRACE: "FALSE"
      BOBCAT_LOCK_FILE: "/etc/bobcat/autopilot.lock"
      BOBCAT_STATE_FILE: "/etc/bobcat/autopilot.json"
      BOBCAT_LOG_FILE: "/var/log/bobcat/autopilot.log"
      #BOBCAT_DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/xxx"
      BOBCAT_LOG_LEVEL_CONSOLE: "DEBUG"
      BOBCAT_LOG_LEVEL_FILE: "DEBUG"
      BOBCAT_LOG_LEVEL_DISCORD: "DEBUG"
    command: autopilot
    stdin_open: true
    build:
      context: .