services:

  # fake bobcat miner service
  fancy-awesome-bobcat:
    image: fancy-awesome-bobcat
    # hostname: fancy-awesome-bobcat
    container_name: fancy-awesome-bobcat
    ports:
      - "80:80"
    build:
      context: ./fancy-awesome-bobcat
      dockerfile: ./Dockerfile
    volumes:
      - ./fancy-awesome-bobcat/src/app:/app
    networks:
      - bobcatnet

  # bobcat-miner-python command line tools
  bobcat-miner-python-dev:
    image: bobcat-miner-python-dev
    hostname: bobcat-miner-python-dev
    container_name: bobcat-miner-python-dev
    environment:
      # BOBCAT_HOSTNAME: "fancy-awesome-bobcat"
      BOBCAT_ANIMAL: "fancy-awesome-bobcat"
      BOBCAT_NETWORKS: "192.168.0.0/24 10.0.0.0/24 172.16.0.0/24 172.18.0.0/24"
      BOBCAT_DRY_RUN: "TRUE"
      BOBCAT_VERBOSE: "FALSE"
      BOBCAT_TRACE: "FALSE"
      BOBCAT_LOCK_FILE: "/etc/bobcat/autopilot.lock"
      BOBCAT_STATE_FILE: "/etc/bobcat/autopilot.json"
      BOBCAT_LOG_FILE: "/var/log/bobcat/autopilot.log"
      # BOBCAT_DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/xxx"
      BOBCAT_LOG_LEVEL_CONSOLE: "DEBUG"
      BOBCAT_LOG_LEVEL_FILE: "DEBUG"
      BOBCAT_LOG_LEVEL_DISCORD: "DEBUG"
    entrypoint: /usr/bin/tail
    command: "-f /dev/null"
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    networks:
      - bobcatnet

networks:
    bobcatnet:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.18.0.0/24
            gateway: 172.18.0.1