# TIME CONSTANTS
ONE_SECOND = 1
ONE_MINUTE = ONE_SECOND * 60
THREE_MINUTES = ONE_MINUTE * 3
FIVE_MINUTES = ONE_MINUTE * 5
TEN_MINUTES = ONE_MINUTE * 10
THIRTY_MINUTES = ONE_MINUTE * 30
ONE_HOUR = ONE_MINUTE * 60
ONE_DAY = ONE_HOUR * 24
