# TIME CONSTANTS
ONE_SECOND: int = 1
ONE_MINUTE: int = ONE_SECOND * 60
THREE_MINUTES: int = ONE_MINUTE * 3
FIVE_MINUTES: int = ONE_MINUTE * 5
TEN_MINUTES: int = ONE_MINUTE * 10
THIRTY_MINUTES: int = ONE_MINUTE * 30
ONE_HOUR: int = ONE_MINUTE * 60
ONE_DAY: int = ONE_HOUR * 24
