name: Lint
on:
  push:
    paths:
      - 'src/**.py'
      - 'tests/**.py'
jobs:
  tests:
    runs-on: ubuntu-20.04
    name: Black code formatting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.10
        architecture: x64
    - run: pip install poetry==1.1.4
    - run: poetry install --no-interaction --no-ansi 
    - run: poetry run black --line-length 100 --check src tests
