name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  poetry_publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.9
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

  docker_push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag
        id: docker_build_with_tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          target: release
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/bobcat:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/bobcat:${{ steps.get_tag.outputs.TAG }}
  
  docker_push_arm32v7:
    needs: poetry_publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag
        id: docker_build_with_tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.arm
          push: true
          platform: linux/arm/v7
          build-args: VERSION=${{ steps.get_tag.outputs.TAG }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/bobcat:latest-arm32v7
            ${{ secrets.DOCKER_HUB_USERNAME }}/bobcat:${{ steps.get_tag.outputs.TAG }}-arm32v7